import { NavBar } from "@/components/navbar";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from "@/lib/registry";
import { GlobalStyle } from "@/styles/global";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Igreja Batista Prudentina",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <GlobalStyle />

          <NavBar />
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
